NVIDIA/NeMo-text-processing

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/close-inactive-issue-pr.yml
- .github/workflows/codeql.yml
- .pre-commit-config.yaml
- requirements/requirements.txt
Signed-off-by: SeanNaren <snarenthiran@nvidia.com>
> Add workflows

- nemo_text_processing/text_normalization/en/data/address/state.tsv
> remove error prone states

- nemo_text_processing/text_normalization/normalize.py
- nemo_text_processing/text_normalization/normalize_with_audio.py
- tests/nemo_text_processing/en/test_normalization_with_audio.py
> Fix AB norm for non Eng, add args description

- nemo_text_processing/text_normalization/en/taggers/range.py
- nemo_text_processing/text_normalization/en/verbalizers/measure.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_normalize_with_audio.txt
- tests/nemo_text_processing/en/test_serial.py
- tests/nemo_text_processing/en/test_word.py
> revert accidental push

- nemo_text_processing/text_normalization/en/taggers/range.py
- nemo_text_processing/text_normalization/en/verbalizers/measure.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_normalize_with_audio.txt
- tests/nemo_text_processing/en/test_serial.py
- tests/nemo_text_processing/en/test_word.py
```python
```
**PR Type**:
- [ X] Bugfix
> pytests bug fix

- nemo_text_processing/inverse_text_normalization/ar/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/ar/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/de/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/de/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/en/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/en/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/es/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/es/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/fr/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/fr/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/pt/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/pt/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/ru/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/ru/verbalizers/verbalize.py
- nemo_text_processing/inverse_text_normalization/vi/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/vi/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/ar/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/ar/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/de/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/de/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/en/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/es/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/es/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/ru/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/zh/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/zh/verbalizers/verbalize.py
Signed-off-by: Jim O'Regan <joregan@kth.se>
Fixes a pair of typos
> fix a pair of typos

- CONTRIBUTING.md
- README.md
Signed-off-by: Yang Zhang <yangzhang@nvidia.com>
```python
```
**PR Type**:
> add contributing

- Jenkinsfile
adds jenkinsfile, credits to @anand-nv 
```python
```
**PR Type**:
> [WIP] add jenkins file

- nemo_text_processing/inverse_text_normalization/ar/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/de/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/de/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/en/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/en/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/es/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/es/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/fr/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/fr/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/inverse_normalize.py
- nemo_text_processing/inverse_text_normalization/pt/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/pt/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/ru/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/ru/taggers/whitelist.py
- nemo_text_processing/inverse_text_normalization/vi/taggers/tokenize_and_classify.py
- nemo_text_processing/inverse_text_normalization/vi/taggers/whitelist.py
- tools/text_processing_deployment/export_grammars.sh
- tools/text_processing_deployment/pynini_export.py
```python
```
**PR Type**:
- [ X] New Feature
> Add whitelist param to ITN

- Jenkinsfile
> update fr cache path for ci

- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile
- nemo_text_processing/fst_alignment/alignment.py
- [x ] Have you signed your commits? Use ``git commit -s`` to sign.
**PR Type**:
- [ x] test
> Align ci test

- Jenkinsfile
- tests/nemo_text_processing/sv/test_cardinal.py
- tests/nemo_text_processing/sv/test_date.py
- tests/nemo_text_processing/sv/test_decimal.py
- tests/nemo_text_processing/sv/test_electronic.py
- tests/nemo_text_processing/sv/test_fraction.py
- tests/nemo_text_processing/sv/test_measure.py
- tests/nemo_text_processing/sv/test_money.py
- tests/nemo_text_processing/sv/test_normalization_with_audio.py
- tests/nemo_text_processing/sv/test_ordinal.py
- tests/nemo_text_processing/sv/test_telephone.py
- tests/nemo_text_processing/sv/test_time.py
- tests/nemo_text_processing/sv/test_whitelist.py
- tests/nemo_text_processing/sv/test_word.py
> Fix SV TN tests

- nemo_text_processing/package_info.py
- requirements/requirements.txt
> 0.1.7 release

- Jenkinsfile
- nemo_text_processing/text_normalization/es/taggers/time.py
- tests/nemo_text_processing/es/data_text_normalization/test_cases_time.txt
fix bug for hh:mm:ss normalization (Spanish)
**PR Type**:
> fix bug for hh:mm:ss normalization

- nemo_text_processing/text_normalization/normalize.py
In text normalizer init(), save `input_case` into a field so that classes which use the normalizer can check what the expected input case is.
Requested by reviewer in https://github.com/NVIDIA/NeMo/pull/6541.
**PR Type**:
> Store input_case in Normalizer

- nemo_text_processing/inverse_text_normalization/fr/graph_utils.py
- nemo_text_processing/inverse_text_normalization/vi/graph_utils.py
- nemo_text_processing/text_normalization/ar/graph_utils.py
- nemo_text_processing/text_normalization/en/graph_utils.py
- nemo_text_processing/text_normalization/zh/graph_utils.py
Replace print statements with logging to avoid noise on stdout
**PR Type**:
> log instead of print in graph_utils.py

- nemo_text_processing/package_info.py
> 0.1.8 release

- nemo_text_processing/inverse_text_normalization/en/data/whitelist_tech.tsv
Adds `whitelist_tech.tsv` containing multiple tech domain related abbreviations 
**PR Type**:
> Add whitelist_tech.tsv

- Jenkinsfile
- nemo_text_processing/inverse_text_normalization/run_evaluate.py
- nemo_text_processing/text_normalization/es/data/ordinals/roman_exceptions.tsv
- nemo_text_processing/text_normalization/es/taggers/ordinal.py
> Es tn romans fix

- Jenkinsfile
Change docker image to one including sparrowhawk
Updates the docker image to one containing sparrowhawk
**PR Type**:
> Change docker image

- nemo_text_processing/text_normalization/normalize.py
- nemo_text_processing/text_normalization/normalize_with_audio.py
Print warning regardless of verbose flag
**PR Type**:
- [ V] New Feature
> warning regardless of verbose flag

- nemo_text_processing/text_normalization/ar/utils.py
- nemo_text_processing/text_normalization/de/utils.py
- nemo_text_processing/text_normalization/en/utils.py
- nemo_text_processing/text_normalization/es/utils.py
- nemo_text_processing/text_normalization/it/utils.py
- nemo_text_processing/text_normalization/ru/utils.py
- nemo_text_processing/text_normalization/zh/utils.py
files opened are not closed.
**PR Type**:
> fixed warnings: File is not always closes.

- nemo_text_processing/text_normalization/it/data/numbers/tens_eight.tsv
- nemo_text_processing/text_normalization/it/taggers/cardinal.py
- nemo_text_processing/text_normalization/it/taggers/time.py
- nemo_text_processing/text_normalization/it/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/it/verbalizers/time.py
- nemo_text_processing/text_normalization/it/verbalizers/verbalize.py
- tests/nemo_text_processing/it/data_text_normalization/test_cases_time.txt
- tests/nemo_text_processing/it/test_sparrowhawk_normalization.sh
- tests/nemo_text_processing/it/test_time.py
Adds TIME class to text normalization for Italian.
**PR Type**:
> Time_IT_TN

- Jenkinsfile
- nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_money.txt
Increase weights for serial (en TN)
**PR Type**:
> Increase weights for serial (en TN)

- Jenkinsfile
- nemo_text_processing/inverse_text_normalization/hy/data/numbers/__init__.py
- nemo_text_processing/inverse_text_normalization/hy/data/ordinals/__init__.py
- nemo_text_processing/inverse_text_normalization/hy/data/time/__init__.py
- nemo_text_processing/text_normalization/hy/data/numbers/__init__.py
- nemo_text_processing/text_normalization/hy/data/ordinal/__init__.py
- nemo_text_processing/text_normalization/hy/data/time/__init__.py
- nemo_text_processing/text_normalization/hy/taggers/tokenize_and_classify.py
> jenkins fix

- Jenkinsfile
- nemo_text_processing/text_normalization/en/data/electronic/domain.tsv
- nemo_text_processing/text_normalization/en/graph_utils.py
- nemo_text_processing/text_normalization/en/taggers/electronic.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_electronic.txt
Fixes the issue where the sentence-final period in sentences ending with domain is incorrectly normalized as part of the domain. The PR also adds a handful of relevant tests and expands on the top-level domain mappings. 
To note: A handful of Sparrowhawk tests failed for the current implementation of EN TN.  This fix does not address those failures.
**PR Type**:
> EN TN fixes for Issue #166

- Jenkinsfile
- requirements/requirements.txt
- requirements/requirements_test.txt
Updates docker container for Jenkins CI to one based out of  http://nvcr.io/nvidia/pytorch:24.07-py3 and bumps up pynini version to 2.1.6
**PR Type**:
> update en tn folder to see if CI tests run - DO NOT MERGE

- Jenkinsfile
- README.md
- nemo_text_processing/text_normalization/en/data/electronic/domain.tsv
- nemo_text_processing/text_normalization/en/graph_utils.py
- nemo_text_processing/text_normalization/en/taggers/electronic.py
- requirements/requirements.txt
- requirements/requirements_test.txt
- tests/nemo_text_processing/en/data_text_normalization/test_cases_electronic.txt
Reverts the changes to the English graph introduced by https://github.com/NVIDIA/NeMo-text-processing/pull/185. 
This PR brings the EN TN grammar back to the state it was in on June 7th, 2024 ([MR](https://github.com/NVIDIA/NeMo-text-processing/pull/181)), before any changes were introduced to the EN TN graph.
The MR contains a block of string variables in `graph_utils.py`, imported by HU TN and IT TN. These are *not* used by the EN TN.  
**PR Type**:
If you haven't finished some of the above items you can …
> Reverts EN TN fixes for Issue #166

- CHANGELOG.md
- nemo_text_processing/package_info.py
> Release commit

- Jenkinsfile
- nemo_text_processing/text_normalization/en/taggers/measure.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_measure.txt
The PR addresses [nv-bug 4786225](https://nvbugspro.nvidia.com/bug/4786225).  
It handles sentences ending in terminal period abbreviations, when followed by another sentence:  
e.g. `Nancy lived on 1428 Elm St. It was a strange place` -> `Nancy lived on fourteen twenty eight Elm Street. It was a strange place.` 
The sentence-final period, which also serves as a component of the abbreviation is left denormalized.
**PR Type**:
> EN TN Fixes for nv-bug 4786225

- Jenkinsfile
- nemo_text_processing/text_normalization/en/taggers/electronic.py
- nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py
- tests/nemo_text_processing/en/data_text_normalization/test_cases_electronic.txt
- tests/nemo_text_processing/en/data_text_normalization/test_cases_money.txt
- tests/nemo_text_processing/en/data_text_normalization/test_cases_range.txt
The fix addresses the following issues reported in [nv-bug 4786263](https://nvbugspro.nvidia.com/bug/4786263):  
- The `"/"` now normalizes correctly to the string `"slash"` in expressions such as `"update/upgrade"`.  This change is applied recursively to support expressions such as `"update/upgrade/downgrade"`.
- Money ranges now normalize correctly (e.g `"$150-$250" -> one hundred and fifty dollars to two hundred and fifty dollars"`).
**PR Type**:
If you haven't finished some of the above items you can …
> Applies fixes for nv-bug 4786263

- Jenkinsfile
- nemo_text_processing/text_normalization/it/data/electronic/domain.tsv
- nemo_text_processing/text_normalization/it/taggers/electronic.py
- nemo_text_processing/text_normalization/it/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/it/verbalizers/electronic.py
- tests/nemo_text_processing/it/data_text_normalization/test_cases_electronic.txt
This PR provides a fix for [Issue #166](https://github.com/NVIDIA/NeMo-text-processing/issues/166) for Italian TN.
**PR Type**:
> IT TN Fixes for Issue #166

- Jenkinsfile
- nemo_text_processing/text_normalization/en/data/money/per_unit.tsv
- tests/nemo_text_processing/en/data_text_normalization/test_cases_address.txt
The current PR expands the list of "currency per unit" mappings contained in `data/money/per_unit.tsv` for EN TN. 
**PR Type**:
> Expands per/unit mappings and updates the cache

- CONTRIBUTING.md
> contributing update

- nemo_text_processing/inverse_text_normalization/en/data/whitelist.tsv
- tests/nemo_text_processing/en/data_inverse_text_normalization/test_cases_whitelist.txt
> Add "at and t" in ITN

- Jenkinsfile
- nemo_text_processing/text_normalization/fr/data/dates/__init__.py
- nemo_text_processing/text_normalization/fr/data/dates/eras.tsv
- nemo_text_processing/text_normalization/fr/data/dates/months.tsv
- nemo_text_processing/text_normalization/fr/taggers/date.py
- nemo_text_processing/text_normalization/fr/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/fr/verbalizers/date.py
- nemo_text_processing/text_normalization/fr/verbalizers/verbalize.py
- tests/nemo_text_processing/fr/data_text_normalization/test_cases_date.txt
- tests/nemo_text_processing/fr/test_date.py
- tests/nemo_text_processing/fr/test_sparrowhawk_normalization.sh
* add base coverage for fr tn date
Signed-off-by: Mariana Graterol Fuenmayor <marianag@nvidia.com>
* [pre-commit.ci] auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
---------
Signed-off-by: Mariana Graterol Fuenmayor <marianag@nvidia.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
**PR Type**:
If you haven't finished some of the above items you can still open …
> Merge FR TN date staging to main

- nemo_text_processing/text_normalization/vi/data/money/__init__.py
- nemo_text_processing/text_normalization/vi/data/money/currency.tsv
- nemo_text_processing/text_normalization/vi/data/money/currency_minor.tsv
- nemo_text_processing/text_normalization/vi/data/money/per_unit.tsv
- nemo_text_processing/text_normalization/vi/data/numbers/quantity_abbr.tsv
- nemo_text_processing/text_normalization/vi/data/time/time_units.tsv
- nemo_text_processing/text_normalization/vi/graph_utils.py
- nemo_text_processing/text_normalization/vi/taggers/cardinal.py
- nemo_text_processing/text_normalization/vi/taggers/decimal.py
- nemo_text_processing/text_normalization/vi/taggers/money.py
- nemo_text_processing/text_normalization/vi/taggers/punctuation.py
- nemo_text_processing/text_normalization/vi/taggers/range.py
- nemo_text_processing/text_normalization/vi/taggers/tokenize_and_classify.py
- nemo_text_processing/text_normalization/vi/taggers/word.py
- nemo_text_processing/text_normalization/vi/verbalizers/decimal.py
- nemo_text_processing/text_normalization/vi/verbalizers/money.py
- nemo_text_processing/text_normalization/vi/verbalizers/verbalize.py
- nemo_text_processing/text_normalization/vi/verbalizers/word.py
- tests/nemo_text_processing/vi/data_text_normalization/test_cases_decimal.txt
- tests/nemo_text_processing/vi/data_text_normalization/test_cases_money.txt
- tests/nemo_text_processing/vi/data_text_normalization/test_cases_range.txt
- tests/nemo_text_processing/vi/data_text_normalization/test_cases_roman.txt
- tests/nemo_text_processing/vi/test_money.py
- tests/nemo_text_processing/vi/test_range.py
- tests/nemo_text_processing/vi/test_sparrowhawk_normalization.sh
- Add money.py tagger and verbalizer for Vietnamese currency handling
- Add range.py tagger for numerical range processing
- Add supporting data files for money (currency, currency_minor, per_unit)
- Add quantity abbreviations and time units data
- Update existing taggers and verbalizers for integration
- Add comprehensive test cases for money and range functionality
- Update tokenize_and_classify to include new semiotic classes
Add Vietnamese TN support for Money and Range semiotic classes
2) Sparrowhawk tests ``bash …
> Add Vietnamese TN support for Money and Range semiotic classes
