Jenkinsfile
nemo_text_processing/inverse_text_normalization/en/data/measurements.tsv
nemo_text_processing/text_normalization/en/data/suppletive.tsv
nemo_text_processing/text_normalization/en/taggers/date.py
nemo_text_processing/text_normalization/en/verbalizers/date.py
tests/nemo_text_processing/en/data_inverse_text_normalization/test_cases_measure.txt
tests/nemo_text_processing/en/data_text_normalization/test_cases_date.txt

Update EN TN and ITN grammars
EN TN date and ITN Measurement
- Add financial period to date in English TN (1Q19)
- Add support for additional measurement in ITN
**PR Type**:

Eng tn itn

---

tools/text_processing_deployment/pynini_export.py

Signed-off-by: Anand Joseph <anajoseph@nvidia.com>
Parse "None" passed as string from bash into NoneType. Without this, "None" is the default string value passed from the bash script which breaks whitelist.

Fix parse "None" as string

---

nemo_text_processing/inverse_text_normalization/fr/taggers/telephone.py
tests/nemo_text_processing/fr/data_inverse_text_normalization/test_cases_telephone.txt

Signed-off-by: Larisa Kempbell <lkempbell@nvidia.com>
```python
```
**PR Type**:

read double digits for telephone grammar

---

nemo_text_processing/text_normalization/normalize.py

rewrite regex to silence deprecation warning

---

Jenkinsfile
nemo_text_processing/text_normalization/sv/taggers/cardinal.py
nemo_text_processing/text_normalization/sv/taggers/decimal.py
nemo_text_processing/text_normalization/sv/taggers/measure.py
nemo_text_processing/text_normalization/sv/taggers/money.py
nemo_text_processing/text_normalization/sv/taggers/telephone.py
nemo_text_processing/text_normalization/sv/taggers/time.py
nemo_text_processing/text_normalization/sv/taggers/tokenize_and_classify.py
nemo_text_processing/text_normalization/sv/taggers/tokenize_and_classify_with_audio.py
nemo_text_processing/text_normalization/sv/utils.py
nemo_text_processing/text_normalization/sv/verbalizers/measure.py
nemo_text_processing/text_normalization/sv/verbalizers/telephone.py
nemo_text_processing/text_normalization/sv/verbalizers/verbalize_final.py

#59 added a fix for the Swedish sparrowhawk script, this adds fixes to make sure the telephone tests pass
**PR Type**:

Swedish telephone fix

---

nemo_text_processing/text_normalization/normalize_with_audio.py
requirements/requirements.txt

The PR replaces `jiwer` with `editdistance` package to speedup CER estimation in audio-based TN.
**PR Type**:

CER estimation speedup for audio-based text normalization

---

tools/text_processing_deployment/pynini_export.py

- [ *] Have you signed your commits? Use ``git commit -s`` to sign.
- [ *] Do all unittests finish successfully before sending PR?
- [ *] If you are adding a new feature: Have you added test cases for both `pytest` and Sparrowhawk [here](tests/nemo_text_processing).
- [ *] Have you added ``__init__.py`` for every folder and subfolder, including `data` folder which has .TSV files?
- [ *] Have you followed codeQL results and removed unused variables …

updated pynini_export.py file to create far files for zh itn

---

nemo_text_processing/inverse_text_normalization/inverse_normalize.py

'sv' was removed from the list of choices when zh itn was added.

readd Swedish

---

requirements/requirements.txt

This PR seeks to support alternate versions of `setuptools` for those (like me) who cannot use the pinned version.
See: https://github.com/NVIDIA/NeMo/issues/7475

Unpin setuptools

---

Jenkinsfile
nemo_text_processing/text_normalization/it/taggers/cardinal.py
tests/nemo_text_processing/it/data_text_normalization/test_cases_cardinal.txt
tests/nemo_text_processing/it/data_text_normalization/test_cases_money.txt
tests/nemo_text_processing/it/data_text_normalization/test_cases_time.txt
tests/nemo_text_processing/it/test_sparrowhawk_normalization.sh
tests/nemo_text_processing/it/test_time.py

Adds test cases for cardinals bug fix in #105 and fixes bug for time tests from same PR.
**PR Type**:

IT TN improvement on tests

---

Jenkinsfile
nemo_text_processing/text_normalization/es/data/ordinals/roman_exceptions.tsv
tests/nemo_text_processing/es/data_text_normalization/test_cases_ordinal.txt

add single letter exception for roman numerals

---

nemo_text_processing/text_normalization/it/taggers/whitelist.py

fix for [issues/122](https://github.com/NVIDIA/NeMo-text-processing/issues/122)
**PR Type**:

fix broken path for nondet whitelist

---

nemo_text_processing/text_normalization/normalize_with_audio.py

Related with issue #152
`text=line['text']` to `text=line[text_field]`

Fix text=line['text'] to text=line[text_field]

---

nemo_text_processing/text_normalization/normalize.py

This changes the docstring in the `split_text_into_sentences` method in `Normalizer()` to a raw string. Without this, there is an invalid escape sequence ('\s') on line 526 in the docstring that can cause a syntax error.
2) Sparrowhawk tests ``bash tools/text_processing_deployment/export_grammars.sh --MODE=test ...``  
**PR Type**:

Use raw docstring in split_text_into_sentences

---

tests/nemo_text_processing/en/test_sparrowhawk_normalization.sh
tools/text_processing_deployment/Dockerfile
tools/text_processing_deployment/docker/launch.sh
tools/text_processing_deployment/pynini_export.py

Add support for postprocessor and preprocessor far in sparrowhawk tests
~~This currently fails since `postprocess.far` has been enabled in sparrowhawk and the test cases do not consider the use of a postprocessor~~
Switch to using a postprocessor when tests are updated. For now reverts to not using postprocessor in tests
**PR Type**:

Sh postprocess

---

nemo_text_processing/inverse_text_normalization/run_evaluate.py
nemo_text_processing/text_normalization/data_loader_utils.py

update evaluation script for ITN to reflect changes with cased grammars
**PR Type**:

update run_evaluate script for cased itn

---

CHANGELOG.md
nemo_text_processing/package_info.py

r1.0.0 Release
- [y ] Have you signed your commits? Use ``git commit -s`` to sign.
- [ y] Do all unittests finish successfully before sending PR?
- [n ] If you are adding a new feature: Have you added test cases for both `pytest` and Sparrowhawk [here](tests/nemo_text_processing).
- [ y] Have you added ``__init__.py`` for every folder and subfolder, including `data` folder which has .TSV files?
- [y ] Have you followed codeQL results and removed unused variables and imports (report is at the bottom of the …

preparing release, updating change log

---

Jenkinsfile
nemo_text_processing/text_normalization/de/data/electronic/domain.tsv
nemo_text_processing/text_normalization/de/taggers/electronic.py
nemo_text_processing/text_normalization/de/taggers/time.py
nemo_text_processing/text_normalization/de/taggers/tokenize_and_classify.py
nemo_text_processing/text_normalization/de/verbalizers/electronic.py
tests/nemo_text_processing/de/data_text_normalization/test_cases_date.txt
tests/nemo_text_processing/de/data_text_normalization/test_cases_decimal.txt
tests/nemo_text_processing/de/data_text_normalization/test_cases_electronic.txt
tests/nemo_text_processing/de/data_text_normalization/test_cases_time.txt
tests/nemo_text_processing/de/test_sparrowhawk_inverse_text_normalization.sh
tests/nemo_text_processing/de/test_sparrowhawk_normalization.sh

This PR implements DE TN fixes for the following issues:
- Adds support for normalizing social media tags (e.g. `@zoobereq` and `@zoobereq.net`)
- Adds support for normalizing comma-separated digit strings
- Adds support for period-separated time formats (e.g. `2.30` and `02.30`)
- Fixes the issue where the final period in sentences ending with a domain name would normalize as part of that domain.
This PR *does not* address the following:
- [The issue with optionally period-separated cardinals](https://github.com/NVIDIA/NeMo-text-processing/issues/171) (e.g. 1 Mil = 100000 | 1.000.000) , which the currently implemented DE TN/ITN doesn't support. The TN and ITN taggers have been rebuilt to accommodate for that hiccup, but since cardinals plug into almost all other DE classes, this issue …

DE TN Fixes

---

Jenkinsfile
nemo_text_processing/text_normalization/it/data/measure/measurements.tsv
tests/nemo_text_processing/it/data_text_normalization/test_cases_measure.txt
tests/nemo_text_processing/it/test_sparrowhawk_normalization.sh

The `%` sign is now accepted by Italian TN (see [this issue](https://github.com/NVIDIA/NeMo-text-processing/issues/171)).
The implementation passes all `pyTest`s but **fails a handful of `Sparrowhawk` tests**.  Since the current fix adds a single mapping, to `nemo_text_processing/text_normalization/it/data/measure/measurements.tsv`, it is unlikely to be related to `Sparrowhawk` failures.
**PR Type**:

IT TN Fixes

---

Jenkinsfile
nemo_text_processing/text_normalization/fr/data/whitelist.tsv
nemo_text_processing/text_normalization/fr/taggers/tokenize_and_classify.py
tests/nemo_text_processing/fr/data_text_normalization/test_cases_whitelist.txt

- The `%` sign is now accepted by French TN ([this issue](https://github.com/NVIDIA/NeMo-text-processing/issues/171)). This is generally implemented as part of the `Measures` class, which French currently lacks. As a stop-gap measure, the `%` was whitelisted. It should be properly implemented as part of `Measures`.
**Note:  This fix was tested with `pyTest` only.  It needs to be tested on `Sparrowhawk` as well.  I was unable to do that since my hardware doesn't have enough memory.**
This PR *does not* address the following:
- The issue with `2`h not normalizing to `deux heures` in FR. Since the abbreviation `h` is subject to declension, this problem should be addressed with the implementation of the `Measures` class. 
1) ``pytest`` or (if your machine does not have GPU) …

FR TN Fixes

---

Jenkinsfile
nemo_text_processing/text_normalization/en/graph_utils.py
nemo_text_processing/text_normalization/it/taggers/electronic.py
nemo_text_processing/text_normalization/it/taggers/tokenize_and_classify.py
nemo_text_processing/text_normalization/it/verbalizers/electronic.py
tests/nemo_text_processing/it/data_text_normalization/test_cases_electronic.txt
tests/nemo_text_processing/it/data_text_normalization/test_cases_whitelist.txt
tests/nemo_text_processing/it/test_sparrowhawk_normalization.sh

A fix for [issue #166](https://github.com/NVIDIA/NeMo-text-processing/issues/166) reported for Italian TN.  Fixes the bug where the sentence-final period in sentences ending with domain is incorrectly normalized as part of the domain. The PR also includes support for social media tags, updated tests and a fix to `test_sparrowhawk_normalization.sh` which blocked Sparrowhawk testing.
**PR Type**:

IT TN Fixes for #166

---

Jenkinsfile
nemo_text_processing/text_normalization/en/graph_utils.py
nemo_text_processing/text_normalization/hu/taggers/electronic.py
nemo_text_processing/text_normalization/hu/taggers/tokenize_and_classify.py
nemo_text_processing/text_normalization/hu/verbalizers/electronic.py
tests/nemo_text_processing/hu/data_text_normalization/test_cases_electronic.txt
tests/nemo_text_processing/hu/test_sparrowhawk_normalization.sh

Fixes the issue where the sentence-final period in sentences ending with domain is incorrectly normalized as part of the domain. The PR also adds support for normalizing social media tags and includes updated tests.
**PR Type**:

HU TN Fixes issue #166

---

Jenkinsfile
nemo_text_processing/text_normalization/en/data/measure/unit.tsv
nemo_text_processing/text_normalization/en/data/money/per_unit.tsv
nemo_text_processing/text_normalization/en/taggers/money.py
nemo_text_processing/text_normalization/en/verbalizers/money.py
tests/nemo_text_processing/en/data_text_normalization/test_cases_money.txt

Fixes [nv-bug #4786175](https://nvbugspro.nvidia.com/bug/4786175).
The fix implements `per_unit` mappings in lieu of morphosyntactic features.  The list of mappings is contained in `nemo_text_processing/text_normalization/en/data/money/per_unit.tsv` and may be expanded to include additional mappings.
**PR Type**:

Fix for nv-bug 4786175

---

.pre-commit-config.yaml
nemo_text_processing/fst_alignment/alignment.py
nemo_text_processing/hybrid/model_utils.py
nemo_text_processing/text_normalization/en/taggers/punctuation.py
nemo_text_processing/text_normalization/en/verbalizers/post_processing.py

This PR fixes SyntaxError issues in Python3.12.
In python3.12, using escape sequences outside of raw strings has been [moved from a deprecation warning into a syntax error](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes), as noted in previous PRs such as #157. As such, I've added a linter to track down cases where we still have this issue and fixed all said reported issues. The original list was as follows:
```
nemo_text_processing/fst_alignment/alignment.py:102:70: W605 invalid escape sequence '\:'
nemo_text_processing/hybrid/model_utils.py:60:26: W605 invalid escape sequence '\s'
nemo_text_processing/hybrid/model_utils.py:60:31: W605 invalid escape sequence '\s'
nemo_text_processing/hybrid/model_utils.py:64:36: W605 invalid escape sequence '\s' …
```

Fix invalid escape sequences

---

Jenkinsfile
nemo_text_processing/text_normalization/es/data/whitelist.tsv
tests/nemo_text_processing/es/data_text_normalization/test_cases_ordinal.txt

Remove "O" and "E" from whitelist. They are conjunctions in Spanish and will commonly appear on their own without being an abbreviation.
**PR Type**:

Fix for issue #211
